[package]
name = "examples"
version.workspace = true
edition = "2021"
publish = false

[dependencies]
encrypt_config = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde = "1"

[[example]]
name = "example"
path = "example.rs"

[[example]]
name = "derive_example"
path = "derive_example.rs"

[features]
default_config_dir = ["encrypt_config/default_config_dir"]
