[package]
name = "encrypt_config_derive"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"

[dev-dependencies]
serde = { version = "1" }
encrypt_config = { workspace = true }

[lib]
proc-macro = true

[features]
default = ["encrypt_config/derive"]
persist = ["encrypt_config/persist"]
secret = ["encrypt_config/secret"]
default_config_dir = ["encrypt_config/default_config_dir"]
