[package]
name = "encrypt_config_derive"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "doc_cfg", "--generate-link-to-definition"]

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"

[dev-dependencies]
serde = { version = "1" }
encrypt_config = { workspace = true }

[lib]
proc-macro = true

[features]
default = []
full = ["persist", "secret"]
persist = []
secret = []
default_config_dir = []
