[package]
name = "encrypt_config"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
documentation.workspace = true

[package.metadata.docs.rs]
features = ["full"]

[dependencies]
snafu = { version = "0.7.5" }
serde = { version = "1", optional = true, features = ["derive"] }
serde_json = { version = "1", optional = true }
rsa = { version = "0.9.6", features = ["serde"], optional = true }
keyring = { version = "2.1.0", optional = true }
rand = { version = "0.8.5", optional = true }
dirs-next = { version = "2.0.0", optional = true }
encrypt_config_derive = { workspace = true, optional = true }

[build-dependencies]
rustc_version = "0.4.0"

[features]
default = ["serde"]
full = ["default", "persist", "secret", "derive"]
serde = ["dep:serde", "dep:serde_json"]
derive = ["dep:encrypt_config_derive"]
secret = ["dep:rsa", "dep:rand", "dep:keyring", "persist", "encrypt_config_derive?/secret"]
persist = [ "save_on_change", "encrypt_config_derive?/persist"]
default_config_dir = ["dep:dirs-next", "encrypt_config_derive?/default_config_dir"]
protobuf = []
save_on_change = []
mock = []
