[package]
name = "encrypt_config"
version.workspace = true
authors.workspace = true
description.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
snafu = { version = "0.7.5" }
serde = { version = "1", optional = true }
serde_json = { version = "1", optional = true }
rsa = { version = "0.9.6", features = ["serde"] }
keyring = "2.1.0"
dirs-next = { version = "2.0.0", optional = true }
rand = "0.8.5"
encrypt_config_derive = { workspace = true, optional = true }

[package.metadata.docs.rs]
features = ["derive"]

[features]
default = ["serde"]
serde = ["dep:serde", "dep:serde_json"]
derive = ["encrypt_config_derive"]
default_config_dir = ["dep:dirs-next", "encrypt_config_derive/default_config_dir"]
protobuf = []
