name: publish

on:
  workflow_dispatch:
    inputs:
      encrypt_config:
        description: "publish encrypt_config"
        type: boolean
        default: false
      encrypt_config_derive:
        description: "publish encrypt_config_derive"
        type: boolean
        default: false

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install cargo components
        run: rustup component add clippy

      - name: login to crates.io
        run: cargo login ${{ secrets.CRATESIO }}

      - name: publish encrypt_config
        if: ${{ inputs.gpt_core }}
        run: .github/scripts/publish_test.sh encrypt_config && .github/scripts/publish.sh encrypt_config

      - name: publish encrypt_config_derive
        if: ${{ inputs.gpt_ui }}
        run: .github/scripts/publish_test.sh encrypt_config_derive && .github/scripts/publish.sh encrypt_config_derive
