name: Publish

on:
  push:
    branches: [dev]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: extract-version
        run: echo "VERSION=$(grep -oP '^version = "\K[^"]+' Cargo.toml | awk '{$1=$1;print}')" >> $GITHUB_OUTPUT

      - name: Cache restore
        uses: actions/cache/restore@v3
        id: cache-cargo-restore
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.extract-version.outputs.VERSION }}

      - name: Run build
        if: steps.cache-cargo-restore.outputs.cache-hit != 'true'
        run: cargo build --all-features --all-targets

      - name: Cache save
        if: steps.cache-cargo-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        id: cache-cargo-save
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ steps.cache-cargo-restore.outputs.cache-primary-key }}

      - name: Run tests
        run: .github/scripts/test.sh

      - name: publish crates dry run
        run: |
          cargo login ${{ secrets.crates_io }}
          cargo publish -p encrypt_config_derive --dry-run
          cargo publish -p encrypt_config --dry-run

      - name: publish crates
        run: |
          cargo publish -p encrypt_config_derive
          cargo publish -p encrypt_config

      - name: Create Tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/v${{ steps.extract-version.outputs.VERSION }}',
                sha: context.sha
            })
