name: Release

on:
  pull_request:
    branches: [release]
    types: [closed]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract version
        id: extract-version
        run: echo "version=$(grep -oP '^version = "\K[^"]+' Cargo.toml | awk '{$1=$1;print}')" >> $GITHUB_OUTPUT

      - name: Cache restore
        uses: actions/cache/restore@v3
        id: cache-cargo-restore
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ steps.extract-version.outputs.version }}

      - name: Run clippy
        run: cargo clippy --all-features --all-targets -- -D warnings

      - name: Run all tests with default features
        run: cargo test

      - name: Run tests(no doc test) with all features
        run: cargo test test --all-features

      - name: publish crates
        uses: katyo/publish-crates@v2
        with:
          # crates.io registry token
          registry-token: ${{ secrets.crates_io }}
